name: Lint front-end code

# **What it does**: Checks code for style using a repository's lint script and optionally applies fixes.
# **Why we have it**: Maintain consistent readability of code.
# **Who does it impact**: Contributors and maintainers.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.js'
      - '**.mjs'
      - '**.ts'
      - '**.tsx'
      - '**.yaml'
      - '**.yml'
      - '**.scss'
      - 'src/**.css'
      - .eslintrc.cjs
      - 'package-lock.json'
      - 'package.json'
      - .github/workflows/lint_js.yml

permissions:
  contents: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-js:
    if: github.repository == 'zachwatkins/.github'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/node-npm-setup

      - name: Run linter
        run: npm run lint
