name: Node set up composite

description: Will set up Node and install all packages by caching node_modules

runs:
  using: 'composite'
  steps:
    - name: Cache node_modules
      uses: actions/cache@v3
      id: cache-node_modules
      env:
        SEGMENT_DOWNLOAD_TIMEOUT_MINS: '1'
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules-${{ hashFiles('package*.json') }}-${{ hashFiles('.github/actions/node-npm-setup/action.yml') }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
        cache: npm

    - name: Install dependencies
      if: ${{ steps.cache-node_modules.outputs.cache-hit != 'true' }}
      shell: bash
      run: npm ci
