name: Move and unlabel "ready to merge" pull requests

# **What it does**: When a pull request in the repository is labeled "ready to merge," the "waiting for review" label is removed.
# **Why we have it**: To help reduce manual work.
# **Who does it impact**: Contributors, maintainers.

on:
  pull_request_target:
    types:
      - labeled

permissions:
  pull-requests: write

jobs:
  unmark_for_review:
    if: github.repository == 'zachwatkins/.github' && github.event.label.name == 'ready to merge'
    runs-on: ubuntu-latest
    steps:
      - name: remove label
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          ignore-if-assigned: 'false'
          remove-labels: 'waiting for review'
