name: Test Laravel Application PHP

on:
  workflow_call:
    inputs:
      php:
        default: "8.2"
        type: string

jobs:
  test:
    if: github.repository == 'zachwatkins/.github'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - uses: ./.github/actions/php-composer-setup

      - name: Generate Laravel application key
        run: php artisan key:generate

      - name: Run tests
        run: php artisan test
