name: Triage new issues

# **What it does**: Add the 'triage' label to new issues in the open source repository.
# **Why we have it**: We want to make sure that new issues are triaged and assigned to the right team.
# **Who does it impact**: Docs open source.

on:
  issues:
    types:
      - reopened
      - opened

permissions:
  issues: write

jobs:
  triage_issues:
    if: ${{ github.repository == 'zachwatkins/.github' }}
    runs-on: ubuntu-latest

    steps:
      - name: Label new issues with 'triage'
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: 'triage'
